import { useMemo, useState } from 'react';
import L from 'leaflet';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './data/i18n';
import type { ParkWaterSafetyEquipmentRecord, ParkWaterSafetyEquipmentSummary, ParkWaterSafetyFacilityCategory } from './types/parkWaterSafety';

const icon = L.divIcon({ className: 'station-marker safety-marker', html: '<span></span>', iconSize: [24, 24], iconAnchor: [12, 12] });
const text = (language: Language, zh: string, en: string) => language === 'zh' ? zh : en;
const labels: Record<Language, Record<ParkWaterSafetyFacilityCategory, string>> = {
  zh: { water_safety_sign: '水域安全告示牌', lifebuoy: '救生圈', lifesaving_equipment: '救生設備', rescue_rope: '救生繩', rescue_pole: '救生竿', combined_sign_and_equipment: '告示牌與救生設備', other: '其他', unknown: '未知' },
  en: { water_safety_sign: 'Water-safety sign', lifebuoy: 'Lifebuoy', lifesaving_equipment: 'Lifesaving equipment', rescue_rope: 'Rescue rope', rescue_pole: 'Rescue pole', combined_sign_and_equipment: 'Sign & equipment', other: 'Other', unknown: 'Unknown' },
};
const notice = (language: Language) => text(language, '點位僅為來源資料位置參考，不代表即時設備狀態、即時可用性、救援保證或現場安全判定。緊急事件請立即聯絡119。', 'The point is only a source-data location reference and does not represent real-time equipment condition, real-time usability, rescue guarantee, or on-site safety determination. For emergencies, contact 119 immediately.');

export default function ParkWaterSafetyPanel({ records, summary, language }: { records: ParkWaterSafetyEquipmentRecord[]; summary: ParkWaterSafetyEquipmentSummary; language: Language }) {
  const [district, setDistrict] = useState('all'); const [park, setPark] = useState('all'); const [category, setCategory] = useState('all'); const [status, setStatus] = useState('all'); const [search, setSearch] = useState(''); const [nearby, setNearby] = useState<Array<ParkWaterSafetyEquipmentRecord & { distance: number }>>([]);
  const districts = useMemo(() => [...new Set(records.map((record) => record.districtNormalized).filter(Boolean))].sort(), [records]);
  const parks = useMemo(() => [...new Set(records.map((record) => record.parkName).filter(Boolean))].sort(), [records]);
  const filtered = useMemo(() => records.filter((record) => (district === 'all' || record.districtNormalized === district) && (park === 'all' || record.parkName === park) && (category === 'all' || record.facilityCategory === category) && (status === 'all' || record.coordinateStatus === status) && (!search.trim() || `${record.districtNormalized} ${record.parkName} ${record.locationDescription} ${record.facilityNameRaw} ${record.equipmentCode} ${record.resourceName}`.toLowerCase().includes(search.trim().toLowerCase()))), [records, district, park, category, status, search]);
  const mapRecords = filtered.filter((record) => record.coordinateStatus === 'valid' && record.latitude !== undefined && record.longitude !== undefined);
  const findNearby = () => navigator.geolocation?.getCurrentPosition(({ coords }) => { const distance = (record: ParkWaterSafetyEquipmentRecord) => { const rad = Math.PI / 180; const a = Math.sin((record.latitude! - coords.latitude) * rad / 2) ** 2 + Math.cos(coords.latitude * rad) * Math.cos(record.latitude! * rad) * Math.sin((record.longitude! - coords.longitude) * rad / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }; setNearby(mapRecords.map((record) => ({ ...record, distance: distance(record) })).sort((a, b) => a.distance - b.distance).slice(0, 6)); });
  const chart = (title: string, data: Array<{ name: string; value: number }>) => <section className="chart-block"><h3>{title}</h3><ResponsiveContainer width="100%" height={240}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" interval={0} angle={-25} textAnchor="end" height={72} /><YAxis /><Tooltip /><Bar dataKey="value" fill="#be123c" /></BarChart></ResponsiveContainer></section>;
  const topPark = summary.byParkName[0];
  const topDistrict = summary.byDistrict[0];
  const categoryCount = (key: ParkWaterSafetyFacilityCategory) => summary.byFacilityCategory.find((item) => item.facilityCategory === key)?.count ?? 0;
  return <section className="river-module"><div className="section-heading"><div><h2>{text(language, '公園水域安全告示牌及救生設備', 'Park Water Safety Signs & Lifesaving Equipment')}</h2><p>{text(language, '查詢臺北市公園水池與湖畔周邊水域安全告示牌及救生設備位置，包含位置、設施名稱、設備編碼與來源座標。', 'Look up Taipei park pond and lakeside water-safety signs and lifesaving equipment locations, including location, facility name, equipment code, and source coordinates.')}</p></div></div>
    <section className="filters river-filters"><label><span>{text(language, '行政區', 'District')}</span><select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{districts.map((value) => <option key={value}>{value}</option>)}</select></label><label><span>{text(language, '公園', 'Park')}</span><select value={park} onChange={(event) => setPark(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{parks.map((value) => <option key={value}>{value}</option>)}</select></label><label><span>{text(language, '設施類型', 'Facility type')}</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{Object.entries(labels[language]).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label><label><span>{text(language, '座標狀態', 'Coordinate status')}</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{['valid', 'missing', 'outlier', 'unparsed'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="search-field"><span>{text(language, '搜尋', 'Search')}</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={text(language, '搜尋行政區、公園、位置、設施名稱或設備編碼', 'Search district, park, location, facility name, or equipment code')} /></label></section>
    <section className="cards">{[[text(language, '水域安全設施紀錄數', 'Water-safety facility record count'), filtered.length], [text(language, '涵蓋行政區數', 'Districts covered'), summary.districtCount], [text(language, '涵蓋公園數', 'Parks covered'), summary.parkCount], [text(language, '有效座標數', 'Valid coordinate count'), filtered.filter((record) => record.coordinateStatus === 'valid').length], [text(language, '水域安全告示牌數', 'Water-safety sign count'), categoryCount('water_safety_sign')], [text(language, '救生設備數', 'Lifesaving equipment count'), categoryCount('lifesaving_equipment') + categoryCount('combined_sign_and_equipment')], [text(language, '救生圈數', 'Lifebuoy count'), categoryCount('lifebuoy')], [text(language, '紀錄最多行政區', 'Top district by record count'), topDistrict ? `${topDistrict.district} ${topDistrict.recordCount}` : '-'], [text(language, '紀錄最多公園', 'Top park by record count'), topPark ? `${topPark.parkName} ${topPark.recordCount}` : '-']].map(([label, value]) => <article className="card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className="map-panel"><div className="section-heading"><h3>{text(language, '地圖', 'Map')}</h3><button onClick={findNearby}>{text(language, '找附近水域安全設施', 'Find nearby water-safety equipment')}</button></div><MapContainer center={[25.04, 121.56]} zoom={11} scrollWheelZoom={false} className="map"><TileLayer attribution='&copy; OpenStreetMap' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{mapRecords.map((record) => <Marker key={record.id} position={[record.latitude!, record.longitude!]} icon={icon}><Popup><strong>{record.facilityNameRaw}</strong><dl><dt>{text(language, '位置', 'Location')}</dt><dd>{record.locationDescription}</dd><dt>{text(language, '設施類型', 'Facility type')}</dt><dd>{labels[language][record.facilityCategory]}</dd><dt>{text(language, '設備編碼', 'Equipment code')}</dt><dd>{record.equipmentCode}</dd><dt>{text(language, '行政區', 'District')}</dt><dd>{record.districtNormalized}</dd><dt>{text(language, '資料來源', 'Source')}</dt><dd>{record.source}</dd></dl><small>{notice(language)}</small></Popup></Marker>)}</MapContainer><p className="empty-map">{text(language, '公園水域安全告示牌及救生設備資料的來源座標標示為TWD97，本網站轉換為WGS84後顯示。點位僅供位置參考，不代表即時設備狀態、即時可用性、救援保證或現場安全判定。', 'The source coordinates for park water-safety signs and lifesaving equipment are described as TWD97. This site converts them to WGS84 before display. Points are for location reference only and do not represent real-time equipment condition, real-time usability, rescue guarantee, or on-site safety determination.')}</p></section>
    {nearby.length > 0 && <section className="notice-block"><h3>{text(language, '附近水域安全設施', 'Nearby Water Safety Equipment')}</h3>{nearby.map((record) => <p key={record.id}>{record.distance < 1 ? `${Math.round(record.distance * 1000)} m` : `${record.distance.toFixed(1)} km`} · {record.locationDescription} · {record.facilityNameRaw}</p>)}<p>{text(language, '附近功能僅依公開資料座標計算距離，不代表設備目前可用、現場安全或救援保證。緊急事件請立即聯絡119，並遵守現場標示與管理單位指示。', 'The nearby feature only calculates distance from public-data coordinates. It does not mean the equipment is currently usable, the site is safe, or rescue is guaranteed. For emergencies, contact 119 immediately and follow on-site signs and site-manager instructions.')}</p></section>}
    <section className="charts">{chart(text(language, '各行政區水域安全設施數', 'Water-safety facilities by district'), summary.byDistrict.map((item) => ({ name: item.district, value: item.recordCount })))}{chart(text(language, '各類型水域安全設施數', 'Water-safety facilities by category'), summary.byFacilityCategory.map((item) => ({ name: labels[language][item.facilityCategory], value: item.count })))}{chart(text(language, '各公園水域安全設施數', 'Water-safety facilities by park'), summary.byParkName.slice(0, 12).map((item) => ({ name: item.parkName, value: item.recordCount })))}{chart(text(language, '座標品質', 'Coordinate quality'), Object.entries(summary.coordinateQuality).map(([name, value]) => ({ name, value })))}{chart(text(language, '來源檔案涵蓋', 'Source resource coverage'), summary.byResourceName.map((item) => ({ name: item.resourceName.replace('公園水域安全告示牌及救生設備位置', '').replace('公園水域安全告示及救生設備位置', ''), value: item.count })))}</section>
    <section className="table-panel"><h3>{text(language, '水域安全設施清單', 'Water Safety Facility Directory')}</h3><div className="table-wrap"><table><thead><tr>{[text(language, '行政區', 'District'), text(language, '公園', 'Park'), text(language, '位置', 'Location'), text(language, '設施名稱', 'Facility name'), text(language, '設施類型', 'Facility type'), text(language, '設備編碼', 'Equipment code'), text(language, '座標狀態', 'Coordinate status'), text(language, '地圖', 'Map')].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{filtered.map((record) => <tr key={record.id}><td>{record.districtNormalized}</td><td>{record.parkName ?? '-'}</td><td>{record.locationDescription}</td><td>{record.facilityNameRaw}</td><td>{labels[language][record.facilityCategory]}</td><td>{record.equipmentCode}</td><td>{record.coordinateStatus}</td><td>{record.coordinateStatus === 'valid' ? `${record.latitude?.toFixed(5)}, ${record.longitude?.toFixed(5)}` : '-'}</td></tr>)}</tbody></table></div></section>
    <section className="notice-block"><p>{text(language, '公園水域安全告示牌及救生設備位置資訊提供臺北市政府工務局公園路燈工程管理處所轄公園內水池及湖畔水域安全告示與救生設備座標位置，欄位包含位置、設施名稱、設備編碼、座標(經度)與座標(緯度)。來源說明標示座標為TWD97，本網站會轉換為WGS84後於地圖呈現。', 'Park water-safety sign and lifesaving equipment location data provides coordinate locations of water-safety signs and lifesaving equipment around ponds and lakesides in parks managed by Taipei City Parks and Street Lights Office. Fields include location, facility name, equipment code, longitude coordinate, and latitude coordinate. The source description states that coordinates are TWD97, so this site converts them to WGS84 before displaying them on the map.')}</p><p>{text(language, '本資料為公園水域安全設施位置公開資料，僅供位置參考與資料查詢，不代表即時設備狀態、即時可用性、救援保證、現場安全判定、游泳安全建議、水質狀態或緊急應變指令。實際現場狀況、設備可用性、禁止事項、水域安全規定與緊急事件請以現場標示、管理單位、119及主管機關公告為準。', 'This data is public location data for park water-safety facilities and is for location reference and lookup only. It does not represent real-time equipment condition, real-time usability, rescue guarantee, on-site safety determination, swimming safety advice, water-quality status, or emergency-response instruction. Actual on-site conditions, equipment usability, prohibited activities, water-safety rules, and emergencies should be verified with on-site signs, site managers, 119 emergency services, and competent-authority announcements.')}</p></section>
  </section>;
}
