import { useMemo, useState } from 'react';
import L from 'leaflet';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './data/i18n';
import type { PumpingStation, PumpingStationSummary } from './types/pumpingStations';

const icon = L.divIcon({ className: 'station-marker', html: '<span>💧</span>', iconSize: [24, 24], iconAnchor: [12, 12] });
const text = (language: Language, zh: string, en: string) => language === 'zh' ? zh : en;
const notice = (language: Language) => text(language, '抽水站資料為臺北市水利處公開之設施位置與基本資料，僅供水利設施分布、河系與行政區探索使用，不代表即時抽水狀態、設備容量、現場開放情形、防洪效果、淹水風險或緊急應變指示。即時水情、防汛資訊與緊急指示請以主管機關正式公告與官方系統為準。', "Pumping station data is public facility-location and basic-information data from Taipei's Hydraulic Engineering Office. It is provided for exploring water-infrastructure distribution, river systems, and districts only. It does not represent real-time pumping status, equipment capacity, site access, flood-control effectiveness, flood risk, or emergency instructions. Real-time information must be verified through official systems.");

export default function PumpingStationsPanel({ records, summary, language }: { records: PumpingStation[]; summary: PumpingStationSummary; language: Language }) {
  const [river, setRiver] = useState('all'); const [district, setDistrict] = useState('all'); const [unit, setUnit] = useState('all'); const [search, setSearch] = useState(''); const [nearby, setNearby] = useState<Array<PumpingStation & { distance: number }>>([]);
  const rivers = useMemo(() => [...new Set(records.map((record) => record.riverSystemNormalized).filter(Boolean))].sort(), [records]);
  const districts = useMemo(() => [...new Set(records.map((record) => record.districtNormalized).filter(Boolean))].sort(), [records]);
  const units = useMemo(() => [...new Set(records.map((record) => record.managementUnit).filter(Boolean))].sort(), [records]);
  const filtered = useMemo(() => records.filter((record) => (river === 'all' || record.riverSystemNormalized === river) && (district === 'all' || record.districtNormalized === district) && (unit === 'all' || record.managementUnit === unit) && (!search.trim() || `${record.stationName} ${record.riverSystem} ${record.district} ${record.managementUnit} ${record.sourceSequenceNumber}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))), [records, river, district, unit, search]);
  const mapRecords = filtered.filter((record) => record.coordinateStatus === 'valid' && record.latitude !== undefined && record.longitude !== undefined);
  const showNearby = () => navigator.geolocation?.getCurrentPosition(({ coords }) => { const distance = (record: PumpingStation) => { const rad = Math.PI / 180; const a = Math.sin((record.latitude! - coords.latitude) * rad / 2) ** 2 + Math.cos(coords.latitude * rad) * Math.cos(record.latitude! * rad) * Math.sin((record.longitude! - coords.longitude) * rad / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }; setNearby(mapRecords.map((record) => ({ ...record, distance: distance(record) })).sort((a, b) => a.distance - b.distance).slice(0, 5)); });
  const chart = (title: string, data: Array<{ name: string; value: number }>) => <section className="chart-block"><h3>{title}</h3><ResponsiveContainer width="100%" height={240}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" interval={0} angle={-25} textAnchor="end" height={72} /><YAxis /><Tooltip /><Bar dataKey="value" fill="#0f766e" /></BarChart></ResponsiveContainer></section>;
  return <section className="river-module"><div className="section-heading"><div><h2>{text(language, '水利處抽水站', 'Pumping Stations')}</h2><p>{text(language, '探索臺北市水利處抽水站位置、河系、行政區、建置日期與管理單位，作為都市排水與防洪設施分布背景。', 'Explore Taipei pumping station locations, river systems, districts, establishment dates, and management units as urban drainage and flood-control infrastructure context.')}</p></div></div>
    <section className="filters river-filters"><label><span>{text(language, '河系', 'River system')}</span><select value={river} onChange={(event) => setRiver(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{rivers.map((value) => <option key={value}>{value}</option>)}</select></label><label><span>{text(language, '行政區', 'District')}</span><select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{districts.map((value) => <option key={value}>{value}</option>)}</select></label><label><span>{text(language, '管理單位', 'Management unit')}</span><select value={unit} onChange={(event) => setUnit(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{units.map((value) => <option key={value}>{value}</option>)}</select></label><label className="search-field"><span>{text(language, '搜尋', 'Search')}</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={text(language, '搜尋站名、河系、行政區或管理單位', 'Search station name, river system, district, or management unit')} /></label></section>
    <section className="cards">{[[text(language, '抽水站數', 'Pumping station count'), filtered.length], [text(language, '有效座標數', 'Valid coordinate count'), filtered.filter((record) => record.coordinateStatus === 'valid').length], [text(language, '河系數', 'River system count'), new Set(filtered.map((record) => record.riverSystemNormalized)).size], [text(language, '涵蓋行政區數', 'Districts covered'), new Set(filtered.map((record) => record.districtNormalized)).size], [text(language, '最早建置日期', 'Earliest establishment date'), summary.minEstablishedDate ?? '-'], [text(language, '最新建置日期', 'Latest establishment date'), summary.maxEstablishedDate ?? '-']].map(([label, value]) => <article className="card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className="map-panel"><div className="section-heading"><h3>{text(language, '地圖', 'Map')}</h3><button onClick={showNearby}>{text(language, '顯示附近抽水站', 'Show nearby pumping stations')}</button></div><MapContainer center={[25.04, 121.56]} zoom={11} scrollWheelZoom={false} className="map"><TileLayer attribution='&copy; OpenStreetMap' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{mapRecords.map((record) => <Marker key={record.id} position={[record.latitude!, record.longitude!]} icon={icon}><Popup><strong>{record.stationName}</strong><dl><dt>{text(language, '河系', 'River system')}</dt><dd>{record.riverSystem}</dd><dt>{text(language, '行政區', 'District')}</dt><dd>{record.district}</dd><dt>{text(language, '建置日期', 'Established date')}</dt><dd>{record.establishedDate}</dd><dt>TWD97 X/Y</dt><dd>{record.xTwd97} / {record.yTwd97}</dd></dl><small>{notice(language)}</small></Popup></Marker>)}</MapContainer></section>
    {nearby.length > 0 && <section className="notice-block"><h3>{text(language, '附近抽水站', 'Nearby pumping stations')}</h3>{nearby.map((record) => <p key={record.id}>{record.distance.toFixed(1)} km · {record.stationName} · {record.riverSystem} · {record.district} · {record.managementUnit}</p>)}<p>{text(language, '抽水站通常為水利設施，未必開放民眾進入。附近功能僅供了解設施分布，不代表可前往、可進入或具即時防災資訊。', 'Pumping stations may not be open to the public. Nearby results only describe facility distribution and do not indicate access or real-time disaster information.')}</p></section>}
    <section className="charts">{chart(text(language, '各河系抽水站數', 'Pumping stations by river system'), summary.byRiverSystem.map((item) => ({ name: item.riverSystem, value: item.count })))}{chart(text(language, '各行政區抽水站數', 'Pumping stations by district'), summary.byDistrict.map((item) => ({ name: item.district, value: item.count })))}{chart(text(language, '建置年代分布', 'Establishment decade distribution'), summary.byEstablishedDecade.map((item) => ({ name: item.decade, value: item.count })))}</section>
    <section className="table-panel"><h3>{text(language, '抽水站清單', 'Pumping Station Directory')}</h3><div className="table-wrap"><table><thead><tr>{['NO', text(language, '站名', 'Station name'), text(language, '河系', 'River system'), text(language, '行政區', 'District'), text(language, '建置日期', 'Established date'), text(language, '管理單位', 'Management unit')].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{filtered.map((record) => <tr key={record.id}><td>{record.sourceSequenceNumber}</td><td>{record.stationName}</td><td>{record.riverSystem}</td><td>{record.district}</td><td>{record.establishedDate}</td><td>{record.managementUnit}</td></tr>)}</tbody></table></div></section><p className="notice-block">{notice(language)}</p></section>;
}
