import { useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './data/i18n';
import type { ReservoirSedimentationSurveyRecord, ReservoirSedimentationSurveySummary } from './types/reservoirSedimentationSurvey';
import { localize as text } from './utils/presentation';

const value = (number: number | null | undefined, compact = false, language: Language = 'en') => number === null || number === undefined ? '—' : compact ? `${(number / 1_000_000).toLocaleString(undefined, { maximumFractionDigits: 2 })} ${text(language, '百萬立方公尺', 'million m³')}` : `${number.toLocaleString()} ${text(language, '立方公尺', 'm³')}`;
const rate = (number: number | null | undefined) => number === null || number === undefined ? '—' : `${number.toLocaleString(undefined, { maximumFractionDigits: 2 })}%`;

export default function ReservoirSedimentationSurveysPanel({ records, summary, language }: { records: ReservoirSedimentationSurveyRecord[]; summary: ReservoirSedimentationSurveySummary; language: Language }) {
  const [startYear, setStartYear] = useState(''); const [endYear, setEndYear] = useState(''); const [validDatesOnly, setValidDatesOnly] = useState(false); const [metric, setMetric] = useState<'capacity' | 'sediment' | 'cumulative' | 'rate'>('capacity'); const [page, setPage] = useState(0);
  const filtered = useMemo(() => records.filter((record) => (!startYear || (record.startYear ?? 0) >= Number(startYear)) && (!endYear || (record.endYear ?? 9999) <= Number(endYear)) && (!validDatesOnly || Boolean(record.endPeriod))).sort((a, b) => (a.endPeriod ?? '').localeCompare(b.endPeriod ?? '')), [records, startYear, endYear, validDatesOnly]);
  const latest = filtered.at(-1); const previous = filtered.at(-2); const capacityChange = latest?.remainingStorageCapacityCubicMeters !== null && previous?.remainingStorageCapacityCubicMeters !== null && latest && previous ? latest.remainingStorageCapacityCubicMeters! - previous.remainingStorageCapacityCubicMeters! : null;
  const chart = filtered.map((record) => ({ period: record.surveyPeriodRaw, date: record.endPeriod ?? record.surveyPeriodRaw, capacity: record.remainingStorageCapacityCubicMeters === null ? null : record.remainingStorageCapacityCubicMeters / 1_000_000, sediment: record.sedimentationVolumeCubicMeters === null ? null : record.sedimentationVolumeCubicMeters / 1_000_000, cumulative: record.cumulativeSedimentationVolumeCubicMeters === null ? null : record.cumulativeSedimentationVolumeCubicMeters / 1_000_000, annual: record.cumulativeAverageAnnualSedimentationCubicMeters === null ? null : record.cumulativeAverageAnnualSedimentationCubicMeters / 1_000_000, rate: record.cumulativeSedimentationRatePercent, interval: record.intervalYears, capacityChange: null as number | null }));
  for (let index = 1; index < chart.length; index += 1) if (chart[index].capacity !== null && chart[index - 1].capacity !== null) chart[index].capacityChange = chart[index].capacity! - chart[index - 1].capacity!;
  const key = metric === 'capacity' ? 'capacity' : metric === 'sediment' ? 'sediment' : metric === 'cumulative' ? 'cumulative' : 'rate';
  const download = () => { const header = ['Survey period', 'Date range', 'Interval years', 'Remaining capacity m3', 'Sedimentation m3', 'Cumulative sedimentation m3', 'Rate percent']; const body = filtered.map((r) => [r.surveyPeriodRaw, r.dateRangeRaw, r.intervalYears, r.remainingStorageCapacityCubicMeters, r.sedimentationVolumeCubicMeters, r.cumulativeSedimentationVolumeCubicMeters, r.cumulativeSedimentationRatePercent].map((cell) => `"${String(cell ?? '').replaceAll('"', '""')}"`).join(',')); const blob = new Blob([[header.join(','), ...body].join('\n')], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'feitsui-reservoir-sedimentation-surveys.csv'; link.click(); URL.revokeObjectURL(link.href); };
  const rows = filtered.slice(page * 12, page * 12 + 12);
  return <section className="river-module"><div className="section-heading"><div><h2>{text(language, '翡翠水庫淤積調查', 'Feitsui Reservoir Sedimentation Surveys')}</h2><p>{text(language, '以歷次調查期別呈現水庫容量與淤積統計，與日常水庫操作資料分開。', 'Survey-period statistics for reservoir capacity and sedimentation, kept separate from daily reservoir operations.')}</p></div></div>
    <p className="notice-block">{text(language, '本資料為翡翠水庫特定調查期別的測量與分析統計，不是即時水位、目前蓄水量或每日淤積監測。', 'This dataset contains long-term statistical results from Feitsui Reservoir sedimentation surveys. The figures are based on measurements and analysis for specific survey periods and are not real-time water levels, current storage readings, or daily sedimentation monitoring.')}</p>
    <section className="filters river-filters"><label><span>{text(language, '起始年', 'Start year')}</span><input type="number" value={startYear} onChange={(event) => { setStartYear(event.target.value); setPage(0); }} /></label><label><span>{text(language, '結束年', 'End year')}</span><input type="number" value={endYear} onChange={(event) => { setEndYear(event.target.value); setPage(0); }} /></label><label><span>{text(language, '有效日期範圍', 'Valid date range')}</span><input type="checkbox" checked={validDatesOnly} onChange={(event) => { setValidDatesOnly(event.target.checked); setPage(0); }} /></label><label><span>{text(language, '指標', 'Metric')}</span><select value={metric} onChange={(event) => setMetric(event.target.value as typeof metric)}><option value="capacity">{text(language, '剩餘總蓄水容量', 'Remaining capacity')}</option><option value="sediment">{text(language, '淤積量', 'Sedimentation volume')}</option><option value="cumulative">{text(language, '累計淤積量', 'Cumulative sedimentation')}</option><option value="rate">{text(language, '累計淤積率', 'Cumulative sedimentation rate')}</option></select></label><button onClick={download}>{text(language, '下載篩選 CSV', 'Download filtered CSV')}</button></section>
    <section className="cards">{[[text(language, '最新期別', 'Latest survey period'), latest?.surveyPeriodRaw ?? '—'], [text(language, '最新調查結束月份', 'Latest survey end month'), latest?.endPeriod ?? '—'], [text(language, '最新剩餘容量', 'Latest remaining capacity'), value(latest?.remainingStorageCapacityCubicMeters, true, language)], [text(language, '最新淤積量', 'Latest sedimentation volume'), value(latest?.sedimentationVolumeCubicMeters, true, language)], [text(language, '累計淤積量', 'Cumulative sedimentation'), value(latest?.cumulativeSedimentationVolumeCubicMeters, true, language)], [text(language, '累計年平均淤積量', 'Cumulative average annual sedimentation'), value(latest?.cumulativeAverageAnnualSedimentationCubicMeters, true, language)], [text(language, '累計淤積率', 'Cumulative sedimentation rate'), rate(latest?.cumulativeSedimentationRatePercent)], [text(language, '調查筆數', 'Survey count'), filtered.length], [text(language, '涵蓋年數', 'Years covered'), `${summary.minYear ?? '—'}–${summary.maxYear ?? '—'}`], [text(language, '推導：前期容量變化', 'Derived: capacity change from prior survey'), capacityChange === null ? '—' : value(capacityChange, false, language)]].map(([label, item]) => <article className="card" key={String(label)}><span>{label}</span><strong>{item}</strong></article>)}</section>
    <section className="charts"><article className="chart-card"><h3>{text(language, '調查期別趨勢', 'Survey-period trend')}</h3><ResponsiveContainer width="100%" height={280}><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" minTickGap={24} /><YAxis unit={metric === 'rate' ? '%' : ' M m³'} /><Tooltip formatter={(n) => metric === 'rate' ? `${n}%` : `${n} million m³`} /><Line type="monotone" dataKey={key} stroke="#2563eb" connectNulls={false} /></LineChart></ResponsiveContainer></article><article className="chart-card"><h3>{text(language, '調查間隔與推導容量變化', 'Survey intervals and derived capacity change')}</h3><ResponsiveContainer width="100%" height={280}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="period" /><YAxis /><Tooltip /><Bar dataKey="interval" fill="#0f766e" /><Bar dataKey="capacityChange" fill="#c2410c" /></BarChart></ResponsiveContainer></article></section>
    <section className="table-panel"><h3>{text(language, '調查紀錄', 'Survey records')}</h3><div className="table-wrap"><table><thead><tr>{[text(language, '期別', 'Survey period'), text(language, '起訖年月', 'Date range'), text(language, '間隔年數', 'Interval'), text(language, '累計間隔', 'Cumulative interval'), text(language, '剩餘容量', 'Remaining capacity'), text(language, '淤積量', 'Sedimentation'), text(language, '累計淤積量', 'Cumulative sedimentation'), text(language, '年平均', 'Annual average'), text(language, '淤積率', 'Rate'), text(language, '推導容量變化', 'Derived capacity change')].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((r, index) => { const prev = filtered[page * 12 + index - 1]; const delta = prev?.remainingStorageCapacityCubicMeters !== null && r.remainingStorageCapacityCubicMeters !== null && prev ? r.remainingStorageCapacityCubicMeters! - prev.remainingStorageCapacityCubicMeters! : null; return <tr key={r.id}><td>{r.surveyPeriodRaw}</td><td>{r.dateRangeRaw}</td><td>{r.intervalYears ?? '—'}</td><td>{r.cumulativeIntervalYears ?? '—'}</td><td>{value(r.remainingStorageCapacityCubicMeters, true, language)}</td><td>{value(r.sedimentationVolumeCubicMeters, true, language)}</td><td>{value(r.cumulativeSedimentationVolumeCubicMeters, true, language)}</td><td>{value(r.cumulativeAverageAnnualSedimentationCubicMeters, true, language)}</td><td>{rate(r.cumulativeSedimentationRatePercent)}</td><td>{value(delta, true, language)}</td></tr>; })}</tbody></table></div><div className="pagination"><button disabled={page === 0} onClick={() => setPage(page - 1)}>{text(language, '上一頁', 'Previous')}</button><span>{page + 1} / {Math.max(1, Math.ceil(filtered.length / 12))}</span><button disabled={(page + 1) * 12 >= filtered.length} onClick={() => setPage(page + 1)}>{text(language, '下一頁', 'Next')}</button></div></section>
    <section className="notice-block"><h3>{text(language, '資料品質與說明', 'Data quality and notes')}</h3><p>{summary.dataQualityWarningCount ? `${summary.dataQualityWarningCount} validation warning(s)` : text(language, '目前無正規化驗證警告。缺失值一律顯示為「—」。', 'No normalization validation warnings. Missing values display as “—”.')}</p><p>{text(language, '剩餘容量、淤積量、累計值與淤積率皆為特定調查期別的來源紀錄；推導變化僅用連續有效調查紀錄計算。本頁不推估水庫壽命、乾旱風險、大壩安全或清淤需求。', 'Remaining capacity, sedimentation volume, cumulative values, and rate are source records for specific survey periods. Derived changes use consecutive valid surveys only. This page does not estimate reservoir lifespan, drought risk, dam safety, or dredging requirements.')}</p></section>
  </section>;
}
