import { useMemo, useState } from 'react';
import L from 'leaflet';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Language } from './data/i18n';
import { localize as text } from './utils/presentation';
import type { SedimentationBasinCatchmentAreaCategory, SedimentationBasinFacilityRecord, SedimentationBasinFacilitySummary } from './types/sedimentationBasins';
import { buildSedimentationBasinFacilitySummary } from './utils/sedimentationBasins';

const icon = L.divIcon({ className: 'station-marker', html: '<span>◒</span>', iconSize: [24, 24], iconAnchor: [12, 12] });
const fmt = (value: number | undefined, digits = 1) => value === undefined || !Number.isFinite(value) ? '-' : value.toFixed(digits).replace(/\.?0+$/, '');
const categoryLabel = (language: Language, category: SedimentationBasinCatchmentAreaCategory) => ({
  zero_or_not_reported: text(language, '零或未回報', 'Zero or not reported'),
  small: text(language, '小型', 'Small'),
  medium: text(language, '中型', 'Medium'),
  large: text(language, '大型', 'Large'),
  very_large: text(language, '特大型', 'Very large'),
  unknown: text(language, '未知', 'Unknown'),
}[category]);
const statusLabel = (language: Language, status: string) => ({
  converted_from_twd97_tm2: text(language, '已由TWD97-TM2轉換', 'Converted from TWD97-TM2'),
  outside_taipei_bounds_after_conversion: text(language, '轉換後超出臺北範圍', 'Outside Taipei bounds after conversion'),
  missing: text(language, '缺少座標', 'Missing'),
  conversion_failed: text(language, '轉換失敗', 'Conversion failed'),
  invalid_source_coordinate: text(language, '來源座標無效', 'Invalid source coordinate'),
  already_wgs84: text(language, '已是WGS84', 'Already WGS84'),
  unknown: text(language, '未知', 'Unknown'),
}[status] ?? status);
const notice = (language: Language) => text(language, '臺北市水利處沉砂池資料提供編號、沉砂池編號、地點、行政區、X坐標、Y坐標與集水區面積等來源欄位，僅供都市水文、排水設施、沉砂池位置與水利基礎設施資料探索使用。本資料不代表即時淹水風險、即時排水能力、設施維護狀態、公共開放狀態、現場安全判斷、工程設計參數、設施邊界、出入口位置、土地或建物風險、保險風險、施工建議、法律意見或官方背書。', 'Taipei sedimentation basin records provide source fields such as custom code, basin code, location name, district, X coordinate, Y coordinate, and catchment area. They are for urban hydrology, drainage facility, sedimentation basin location, and water infrastructure data exploration only. This data does not represent real-time flooding risk, real-time drainage capacity, facility maintenance status, public access status, on-site safety judgment, engineering design parameters, facility boundary, entrance location, land or building risk, insurance risk, construction advice, legal advice, or official endorsement.');

export default function SedimentationBasinsPanel({ records, summary: _summary, language }: { records: SedimentationBasinFacilityRecord[]; summary: SedimentationBasinFacilitySummary; language: Language }) {
  const [district, setDistrict] = useState('all'); const [category, setCategory] = useState('all'); const [validOnly, setValidOnly] = useState(false); const [search, setSearch] = useState('');
  const districts = useMemo(() => [...new Set(records.map((record) => record.districtNameNormalized).filter(Boolean))].sort(), [records]);
  const categories = useMemo(() => [...new Set(records.map((record) => record.catchmentAreaCategory))], [records]);
  const filtered = useMemo(() => records.filter((record) => (district === 'all' || record.districtNameNormalized === district) && (category === 'all' || record.catchmentAreaCategory === category) && (!validOnly || record.coordinateValid) && (!search.trim() || `${record.customCode} ${record.poolCode} ${record.poolName} ${record.districtName} ${record.catchmentAreaRaw}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()))), [records, district, category, validOnly, search]);
  const filteredSummary = useMemo(() => buildSedimentationBasinFacilitySummary(filtered), [filtered]);
  const summary = filteredSummary;
  const groups = useMemo(() => [...new Map(filtered.filter((record) => record.coordinateValid && record.latitude !== undefined && record.longitude !== undefined).map((record) => [record.coordinatePairKey!, [] as SedimentationBasinFacilityRecord[]])).keys()].map((key) => filtered.filter((record) => record.coordinatePairKey === key)), [filtered]);
  const chart = (title: string, data: Array<{ name: string; value: number }>) => <section className="chart-block"><h3>{title}</h3><ResponsiveContainer width="100%" height={240}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" interval={0} angle={-25} textAnchor="end" height={72} /><YAxis /><Tooltip /><Bar dataKey="value" fill="#0f766e" /></BarChart></ResponsiveContainer></section>;
  const topDistrictByArea = [...filteredSummary.byDistrict].sort((a, b) => (b.totalCatchmentArea ?? 0) - (a.totalCatchmentArea ?? 0))[0];
  return <section className="river-module"><div className="section-heading"><div><h2>{text(language, '臺北市水利處沉砂池', 'Taipei Sedimentation Basin Facilities')}</h2><p>{text(language, '查詢臺北市沉砂池位置、行政區、沉砂池編號、來源座標與集水區面積，作為都市水文、排水設施與水利基礎設施資料參考。', 'Explore Taipei sedimentation basin locations, districts, basin codes, source coordinates, and catchment areas as urban hydrology, drainage facility, and water infrastructure reference data.')}</p></div></div>
    <section className="filters river-filters"><label><span>{text(language, '行政區', 'District')}</span><select value={district} onChange={(event) => setDistrict(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{districts.map((value) => <option key={value}>{value}</option>)}</select></label><label><span>{text(language, '集水區面積類別', 'Catchment area category')}</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">{text(language, '全部', 'All')}</option>{categories.map((value) => <option key={value} value={value}>{categoryLabel(language, value)}</option>)}</select></label><label><span>{text(language, '有有效轉換座標', 'Has valid converted coordinates')}</span><input type="checkbox" checked={validOnly} onChange={(event) => setValidOnly(event.target.checked)} /></label><label className="search-field"><span>{text(language, '搜尋', 'Search')}</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={text(language, '搜尋沉砂池編號、地點、行政區或集水區面積', 'Search basin code, location, district, or catchment area')} /></label></section>
    <section className="cards">{[[text(language, '沉砂池紀錄數', 'Sedimentation basin record count'), filtered.length], [text(language, '涵蓋行政區數', 'Districts covered'), new Set(filtered.map((record) => record.districtNameNormalized)).size], [text(language, '有效轉換座標紀錄數', 'Valid converted coordinate record count'), filtered.filter((record) => record.coordinateValid).length], [text(language, '重複座標組數', 'Duplicate coordinate pair count'), summary.duplicateCoordinatePairCount], [text(language, '集水區面積合計', 'Total catchment area'), fmt(summary.totalCatchmentArea, 0)], [text(language, '平均集水區面積', 'Average catchment area'), fmt(summary.averageCatchmentArea)], [text(language, '最大集水區面積', 'Largest catchment area'), fmt(summary.maxCatchmentArea, 0)], [text(language, '沉砂池最多行政區', 'District with most basins'), summary.byDistrict[0]?.districtName ?? '-'], [text(language, '集水區面積合計最大行政區', 'District with largest total catchment area'), topDistrictByArea?.districtName ?? '-'], [text(language, '集水區面積最大沉砂池', 'Basin with largest catchment area'), summary.topBasinsByCatchmentArea[0]?.poolName ?? '-']].map(([label, value]) => <article className="card" key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
    <section className="map-panel"><div className="section-heading"><div><h3>{text(language, '沉砂池分布圖', 'Sedimentation Basin Distribution Map')}</h3><p>{text(language, '依來源TWD97-TM2座標轉換後之經緯度顯示沉砂池參考點位，僅供公開資料查詢。', 'Shows sedimentation basin reference points using coordinates converted from source TWD97-TM2 coordinates for public-record lookup only.')}</p></div></div><MapContainer center={[25.04, 121.56]} zoom={11} scrollWheelZoom={false} className="map"><TileLayer attribution='&copy; OpenStreetMap' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{groups.map((items) => <Marker key={items[0].coordinatePairKey} position={[items[0].latitude!, items[0].longitude!]} icon={icon}><Popup>{items.map((record) => <div key={record.id}><strong>{record.poolCode} · {record.poolName}</strong><dl><dt>{text(language, '行政區', 'District')}</dt><dd>{record.districtName}</dd><dt>{text(language, '集水區面積', 'Catchment area')}</dt><dd>{record.catchmentAreaRaw || '-'}</dd><dt>WGS84</dt><dd>{record.latitude?.toFixed(6)}, {record.longitude?.toFixed(6)}</dd><dt>TWD97 X/Y</dt><dd>{record.sourceCoordinateX} / {record.sourceCoordinateY}</dd></dl></div>)}<small>{text(language, '此資料為沉砂池來源紀錄，僅供公開資料查詢。請勿將其解讀為即時淹水風險、設施維護狀態、公共開放狀態、現場安全判斷、排水能力保證或工程設計資訊。', 'This is a source record from the sedimentation basin dataset and is for public-data lookup only. Do not interpret it as real-time flooding risk, facility maintenance status, public access status, on-site safety judgment, drainage-capacity guarantee, or engineering design information.')}</small></Popup></Marker>)}</MapContainer></section>
    <section className="charts">{chart(text(language, '各行政區沉砂池數', 'Basins by district'), filteredSummary.byDistrict.map((item) => ({ name: item.districtName, value: item.count })))}{chart(text(language, '各行政區集水區面積合計', 'Total catchment area by district'), filteredSummary.byDistrict.map((item) => ({ name: item.districtName, value: item.totalCatchmentArea ?? 0 })))}{chart(text(language, '集水區面積類別分布', 'Catchment area category distribution'), filteredSummary.byCatchmentAreaCategory.map((item) => ({ name: categoryLabel(language, item.catchmentAreaCategory), value: item.count })))}{chart(text(language, '集水區面積最大沉砂池', 'Top basins by catchment area'), filteredSummary.topBasinsByCatchmentArea.slice(0, 10).map((item) => ({ name: item.poolCode, value: item.catchmentArea })))}</section>
    <section className="table-panel"><h3>{text(language, '沉砂池清單', 'Sedimentation Basin Directory')}</h3><div className="table-wrap"><table><thead><tr>{[text(language, '編號', 'Custom code'), text(language, '沉砂池編號', 'Basin code'), text(language, '地點', 'Location'), text(language, '行政區', 'District'), text(language, '集水區面積', 'Catchment area'), text(language, '座標轉換狀態', 'Coordinate conversion status'), text(language, '地圖查詢', 'Map lookup')].map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{filtered.map((record) => <tr key={record.id}><td>{record.customCode}</td><td>{record.poolCode}</td><td>{record.poolName}</td><td>{record.districtName}</td><td>{record.catchmentAreaRaw}</td><td>{statusLabel(language, record.coordinateConversionStatus)}</td><td>{record.googleMapsQuery ? <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(record.googleMapsQuery)}`} target="_blank" rel="noreferrer">{text(language, '查詢', 'Lookup')}</a> : '-'}</td></tr>)}</tbody></table></div></section>
    <section className="notice-block"><p>{notice(language)}</p><p>{text(language, '本資料提供TWD97-TM2座標X與座標Y，並非直接可用之WGS84經緯度。本網站會先進行座標轉換與臺北範圍驗證，再顯示地圖點位。來源點位僅代表沉砂池參考位置，不代表設施邊界、入口、公共開放範圍、工程範圍或現場可進入位置。', 'This data provides TWD97-TM2 coordinate X and coordinate Y, not directly usable WGS84 longitude and latitude. This site converts the source coordinates and validates them against Taipei bounds before showing map points. Source points represent sedimentation basin reference locations only and do not represent facility boundaries, entrances, public access areas, engineering extents, or on-site accessible locations.')}</p></section>
  </section>;
}
